[build]
  command = "bunx xyd-js build"
  publish = ".xyd/build/client"

[build.environment]
  BUN_VERSION = "1.1.20"

[[redirects]]
  from = "/"
  to = "/docs/guides/introduction/"
  status = 301
  force = true

[[redirects]]
  from = "/index.html"
  to = "/docs/guides/introduction/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/guides"
  to = "/docs/guides/introduction"
  status = 301
  force = true

[[redirects]]
  from = "/docs"
  to = "/docs/guides/introduction"
  status = 301
  force = true

[[redirects]]
  from = "/docs/reference/core"
  to = "/docs/reference/core/overview"
  status = 301
  force = true

