name: 🧪 Release Notes Manual

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to create release for (e.g., v1.2.3)'
        required: true
        type: string
      previous_tag:
        description: 'Previous tag to compare against (optional)'
        required: false
        type: string
        default: ''

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Generate release notes
        id: release_notes
        env:
          # for your Node script's fetch() calls
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          set -euo pipefail

          VERSION="${{ github.event.inputs.version }}"
          PREV="${{ github.event.inputs.previous_tag }}"

          if [ -n "$PREV" ]; then
            RELEASE_BODY="$(node ./scripts/release-notes.mjs "$VERSION" "$PREV")"
          else
            RELEASE_BODY="$(node ./scripts/release-notes.mjs "$VERSION")"
          fi

          {
            echo "RELEASE_BODY<<EOF"
            echo "$RELEASE_BODY"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Create release
        env:
          # gh CLI uses GH_TOKEN (or GITHUB_TOKEN)
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ github.event.inputs.version }}" \
            --title "${{ github.event.inputs.version }}" \
            --notes "${{ steps.release_notes.outputs.RELEASE_BODY }}"
